apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-crds
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 78.2.0
    helm:
      values: |
        prometheusOperator:
          installCRDs: true
        grafana:
          enabled: false
        prometheus:
          enabled: false
        alertmanager:
          enabled: false
        kubeStateMetrics:
          enabled: false
        nodeExporter:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
