apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://charts.wordpress.org/
    chart: wordpress
    targetRevision: 16.0.0 # verifique versão estável no repositório
    helm:
      values: |
        service:
          type: ClusterIP
        wordpressUsername: admin
        wordpressPassword: changeme
        wordpressEmail: admin@example.com
        wordpressFirstName: Admin
        wordpressLastName: User
        wordpressBlogName: Meu Blog
        persistence:
          enabled: true
          size: 8Gi
        mariadb:
          enabled: true
          architecture: standalone
          primary:
            persistence:
              enabled: true
              size: 8Gi

        # Exposição de métricas via sidecar + ServiceMonitor
        metrics:
          enabled: true
          image:
            repository: ghcr.io/prometheuscommunity/wordpress-exporter
            tag: latest
          port: 9117
          path: /metrics
          serviceMonitor:
            enabled: true
            namespace: monitoring
            interval: 30s
            scrapeTimeout: 10s
            additionalLabels:
              release: kube-prometheus-stack

  destination:
    server: https://kubernetes.default.svc
    namespace: wordpress

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
