apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: argocd
spec:
  project: default
  source:
    # Novo repositório OCI da Bitnami Charts
    repoURL: oci://registry-1.docker.io/bitnamicharts/wordpress
    targetRevision: latest   # usa a tag 'latest', que é a única mantida publicamente
    helm:
      values: |
        wordpressUsername: admin
        wordpressPassword: admin123
        wordpressEmail: admin@example.com
        wordpressBlogName: "Meu Blog WordPress"
        service:
          type: ClusterIP

        mariadb:
          enabled: true
          auth:
            rootPassword: rootpassword
            username: bn_wordpress
            password: wordpresspass
            database: bitnami_wordpress

        persistence:
          enabled: true
          size: 4i

        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
            namespace: monitoring
            additionalLabels:
              release: kube-prometheus-stack

  destination:
    server: https://kubernetes.default.svc
    namespace: wordpress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
