apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: wordpress
    targetRevision: 27.0.10
    helm:
      values: |
        service:
          type: ClusterIP

        wordpressUsername: admin
        wordpressPassword: changeme
        wordpressEmail: admin@example.com
        wordpressFirstName: Admin
        wordpressLastName: User
        wordpressBlogName: Meu Blog

        persistence:
          enabled: true
          size: 4Gi

        mariadb:
          enabled: true
          architecture: standalone
          auth:
            rootPassword: rootpassword
            password: wordpresspassword
          primary:
            persistence:
              enabled: true
              size: 4Gi

        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
            namespace: monitoring
            interval: 30s
            scrapeTimeout: 10s
            additionalLabels:
              release: kube-prometheus-stack

  destination:
    server: https://kubernetes.default.svc
    namespace: wordpress

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
