apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: wordpress
    # Use uma versão atual compatível — verificado no ArtifactHub
    targetRevision: 25.0.8  # exemplo de versão recente :contentReference[oaicite:4]{index=4}
    helm:
      values: |
        wordpressUsername: admin
        wordpressPassword: admin123
        wordpressEmail: admin@example.com
        wordpressBlogName: "Meu Blog WordPress"
        service:
          type: ClusterIP
        mariadb:
          enabled: true
          auth:
            rootPassword: rootpassword
            username: bn_wordpress
            password: wordpresspass
            database: bitnami_wordpress
        persistence:
          enabled: true
          size: 4Gi
        metrics:
          enabled: true           # ativa o exporter para métricas :contentReference[oaicite:5]{index=5}
          serviceMonitor:
            enabled: true
            namespace: monitoring
            additionalLabels:
              release: kube-prometheus-stack
  destination:
    server: https://kubernetes.default.svc
    namespace: wordpress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
